// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJgzhIFd8FjJbTHz3WTD5qMbzGC_GD5fI',
    appId: '1:286871696524:web:cd78805a37348bc123b7a9',
    messagingSenderId: '286871696524',
    projectId: 'deepfakedetectionproject-738aa',
    authDomain: 'deepfakedetectionproject-738aa.firebaseapp.com',
    storageBucket: 'deepfakedetectionproject-738aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzRM4gPbQw3cG10eZ3wrfd2HKCjVRlois',
    appId: '1:286871696524:android:61aba493ca4f1ad323b7a9',
    messagingSenderId: '286871696524',
    projectId: 'deepfakedetectionproject-738aa',
    storageBucket: 'deepfakedetectionproject-738aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4hsFSi7M-R5yVwsCP6tO5o4NEiMoHFds',
    appId: '1:286871696524:ios:ef00f3fce913192623b7a9',
    messagingSenderId: '286871696524',
    projectId: 'deepfakedetectionproject-738aa',
    storageBucket: 'deepfakedetectionproject-738aa.firebasestorage.app',
    iosBundleId: 'com.mycompany.deepfakedetection',
  );
}
